<a href="https://colab.research.google.com/github/bu11ymaguire/studying/blob/main/Bandit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#임의의 승률에 대해 이길 수 있는 슬롯머신 10대 구현

In [1]:
import numpy as np

class Bandit:
  def __init__(self, arms = 10):
    self.rates = np.random.rand(arms)

  def play(self, arm):
    rate = self.rates[arm]

    if rate > np.random.rand():
      return 1
    else:
      return 0

In [3]:
bandit = Bandit()

In [5]:
for i in range(10):
  print(bandit.play(0))

0
1
1
1
0
1
0
0
1
0


#에이전트 구현

## 증분 구현

In [6]:
bandit = Bandit()
Q = 0

for n in range(1,11):
  reward = bandit.play(0)
  Q += (reward - Q) / n
  print(Q)

0.0
0.0
0.0
0.0
0.2
0.16666666666666669
0.14285714285714288
0.12500000000000003
0.11111111111111113
0.10000000000000002


## 슬롯머신 가치 추정기 갱신

In [7]:
bandit = Bandit()
Qs = np.zeros(10)
ns = np.zeros(10)

for n in range(10):
  action = np.random.randint(0,10)
  reward = bandit.play(action)

  ns[action] += 1
  Qs[action] += (reward - Qs[action]) / ns[action]
  print(Qs)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[0.33333333 0.         1.         0.         0.         0.
 0.         0.         0.         0.        ]
[0.25 0.   1.   0.   0.   0.   0.   0.   0.   0.  ]
[0.25 0.   1.   0.   0.   0.   1.   0.   0.   0.  ]
[0.25 0.   1.   0.   0.   0.   1.   0.   0.   0.  ]


#Agent 구현

In [8]:
class Agent:
  def __init__(self, epsilon, action_size = 10):
    self.epsilon = epsilon  # 탐색확률
    self.Qs = np.zeros(action_size)
    self.ns = np.zeros(action_size)

  def update(self, action, reward): # 가치추정
    self.ns[action] +=1
    self.Qs[action] += (reward - self.Qs[action]) / self.ns[action]

  def get_action(self): #행동 선택
    if np.random.rand() < self.epsilon:
      return np.random.randint(0, len(self.Qs))
    return np.argmax(self.Qs)

## 에이전트는 epsilon이라는 확률에 따라서 탐색을 진행하거나 아니면, 가치 추정치가 가장 큰 행동을 선택한다.

In [ ]:
#실행